Feature/7 db
pjbeltran/oxygen-cs-grp1-eq23 pull request #10
Opened 2023-10-26 20:47 UTC by KookyEddie

AJout de tests pour les fonctionnalités

2023-10-26 21:39 UTC, pjbeltran requested changes
Juste garder le contenu du dossier readme et mettre le contenu pour le rapport dans un autre readme.md dans un dossier docs

2023-10-26 21:39 UTC, pjbeltran commented on README.md
Je pense qu'on devrait garder le contenu de ce fichier et pour la documentation, on le fait dans un autre fichier readme dans un dossier docs

2023-10-27 16:06 UTC, KookyEddie commented on README.md
j'ai fais le changement pour le read me

2023-10-28 14:45 UTC, pjbeltran requested changes
Remettre la fonction def __del__(self)

2023-10-28 14:45 UTC, pjbeltran commented on src/main.py
> -    def __del__(self):
Cette fonction ne doit pas etre supprimer, elle permet de garantir que lors de la "destruction" de l'objet, la connexion se ferme bien

2023-10-29 02:06 UTC, KookyEddie commented on src/main.py
> -    def __del__(self):
Le changement est fait, j'ai ajouter la fonction

2023-10-29 17:44 UTC, pjbeltran approved these changes

2023-10-29 17:45 UTC, merged